
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;


import Categoria.FrmCategoria;
import Cliente.FrmCliente;
import Cuentas.FrmCuentaCobrar;
import DevolucionCliente.AnularFactura;
import DevolucionCliente.FrmFacturas;
import Facturacion.FrmFactura;
import Producto.FrmProducto;
import Proveedor.FrmProveedor;
import Usuario.FrmUsuario;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author Jonathan
 */
public class Principal extends javax.swing.JFrame implements Runnable {

    FrmFactura frmFactura=new FrmFactura();
    String hora,minutos,segundos,ampm;
    Thread h1;
    //instancia de la clase calendar
    
    Calendar calendario = Calendar.getInstance();
    
    //variables que contendran la fecha y hora
    
    int dia=calendario.get(Calendar.DAY_OF_WEEK);
    int diaNumero=calendario.get(Calendar.DAY_OF_MONTH);
    int mes=calendario.get(Calendar.MONTH);
    int anio=calendario.get(Calendar.YEAR);
    /*
    int hora=calendario.get(Calendar.HOUR);
    int minuto=calendario.get(Calendar.MINUTE);
    int segundos=calendario.get(Calendar.SECOND);
    */
    //vector que contiene los dias de la semana
    String[] dias={"Domingo","Lunes","Martes", "Miércoles","Jueves","Viernes","Sábado"};
    String[] meses={"Enero","Febrero","Marzo", "Abril","Mayo","Junio","Juliio","Agosto",
                    "Septiembre","Octubre","Noviembre","Diciembre"};

    
    //--------------------------------------------------------------------------
    //Aqui se crean instacias de las ventanas para asi poder llamarlas
    
    ///-------------------------------------------------------------------------
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        //se asigna los valores de la fecha a la etiqueta
        lblfecha.setText(dias[dia-1]+" "+diaNumero+" de "+meses[mes]+" del "+anio);
        //lblHora.setText(hora+":"+minuto+":"+segundos);
        h1 = new Thread(this);
        h1.start();
        setTitle("LIBRERIA Y BAZAR LETTY"); //Titulo del frame
        setLocationRelativeTo(null); //Para centrar la ventana
        setVisible(true);
            
       // HoraActual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblUsua = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnBuscarProveedor = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnBuscarProducto = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnCuentaCobrar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnCuentaPagar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnVender = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        btnCuentaCobrar1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        btnIngresarPedido = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSalir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuVentaCredito = new javax.swing.JMenu();
        menuVentasCredito = new javax.swing.JMenuItem();
        menuMantenimientoCategoria = new javax.swing.JMenu();
        menuMantenimientoarticulo = new javax.swing.JMenuItem();
        menuMantenimientoClientes = new javax.swing.JMenuItem();
        menuMantenimientoProveedores = new javax.swing.JMenuItem();
        menuManteCategoria = new javax.swing.JMenuItem();
        menuIngresarPedido = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menuVentasDiario = new javax.swing.JMenuItem();
        menuVentasMensual = new javax.swing.JMenuItem();
        MenuVentasTrimestral = new javax.swing.JMenuItem();
        MenuVentasSemestral = new javax.swing.JMenuItem();
        MenuVentasAnual = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenuComprasMensual = new javax.swing.JMenuItem();
        MenuComprasTrimestral = new javax.swing.JMenuItem();
        MenuComprasSemestral = new javax.swing.JMenuItem();
        MenuComprasAnual = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        MenuDevolucionProveedor = new javax.swing.JMenuItem();
        MenuDevolucionCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIBRERÍA Y BAZAR LETTY");

        jPanel1.setMinimumSize(new java.awt.Dimension(1360, 768));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1360, 768));
        jPanel2.setPreferredSize(new java.awt.Dimension(1360, 768));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(70, 99, 138));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha: ");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 11, 78, 28);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fo - copia.jpg"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(801, 11, 550, 493);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hora:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(574, 11, 58, 28);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BIENVENIDOS LIBRERÍA Y BAZAR ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 133, 790, 56);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LETTY");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(317, 195, 151, 56);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("USUARIO:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 470, 114, 28);

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblUsuario);
        lblUsuario.setBounds(274, 411, 0, 0);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("¡ES UN PLACER SERVIRLE!");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(84, 285, 631, 56);

        lblFecha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblFecha);
        lblFecha.setBounds(97, 11, 415, 29);

        lblHora.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblHora);
        lblHora.setBounds(638, 11, 153, 25);

        lblUsua.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblUsua.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblUsua);
        lblUsua.setBounds(130, 470, 138, 30);
        lblUsua.getAccessibleContext().setAccessibleName("lblUsuario");

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 93, 1360, 0);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-employee-icon-19449707.jpg"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(319, 0, 97, 59);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Cliente");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(338, 65, 56, 22);

        btnBuscarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lorry-icon.png"))); // NOI18N
        btnBuscarProveedor.setContentAreaFilled(false);
        btnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarProveedor);
        btnBuscarProveedor.setBounds(113, 0, 97, 59);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Proveedor");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(123, 65, 85, 22);

        btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/codigoBarra - copia.jpg"))); // NOI18N
        btnBuscarProducto.setContentAreaFilled(false);
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarProducto);
        btnBuscarProducto.setBounds(216, 0, 97, 59);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Artículos");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(226, 65, 80, 22);

        btnCuentaCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cobrar - copia.jpg"))); // NOI18N
        btnCuentaCobrar.setContentAreaFilled(false);
        btnCuentaCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaCobrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCuentaCobrar);
        btnCuentaCobrar.setBounds(525, 0, 97, 59);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Cta.Cobrar");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(535, 65, 90, 22);

        btnCuentaPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/money-icon.png"))); // NOI18N
        btnCuentaPagar.setContentAreaFilled(false);
        btnCuentaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaPagarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCuentaPagar);
        btnCuentaPagar.setBounds(422, 0, 97, 59);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("Cta.Pagar");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(432, 65, 82, 22);

        btnVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venta - copia.jpg"))); // NOI18N
        btnVender.setContentAreaFilled(false);
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });
        jPanel2.add(btnVender);
        btnVender.setBounds(10, 0, 97, 59);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setText("Facturar");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 65, 69, 22);

        jLabel36.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel36.setText("COMERCIAL CACHAGUI S.A");
        jPanel2.add(jLabel36);
        jLabel36.setBounds(20, 660, 310, 20);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Santa Cecilia, La Cruz,GTE");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(20, 640, 310, 20);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("CÉDULA JURIDICA 3-101-3126-36-15");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(400, 620, 310, 20);

        jLabel38.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel38.setText("LUBRICENTRO SANTA CECILIA Tele 71289199");
        jPanel2.add(jLabel38);
        jLabel38.setBounds(10, 620, 370, 20);

        btnCuentaCobrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cobrar - copia.jpg"))); // NOI18N
        btnCuentaCobrar1.setContentAreaFilled(false);
        jPanel2.add(btnCuentaCobrar1);
        btnCuentaCobrar1.setBounds(525, 0, 97, 59);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setText("Cta.Cobrar");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(535, 65, 90, 22);

        btnIngresarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/devolucion.png"))); // NOI18N
        btnIngresarPedido.setContentAreaFilled(false);
        btnIngresarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPedidoActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresarPedido);
        btnIngresarPedido.setBounds(630, 0, 97, 59);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setText("Ingr.Pedido");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(640, 62, 100, 30);

        jPanel4.setBackground(new java.awt.Color(70, 95, 130));
        jPanel4.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lbricentro.jpg"))); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(960, 10, 330, 330);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("¡ES UN PLACER SERVILE!");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(200, 190, 541, 58);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("LUBRICENTRO SANTA CECILIA");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(126, 130, 680, 58);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("FECHA:");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(22, 11, 80, 29);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("HORA:");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(569, 11, 71, 29);

        lblfecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha.setText("FECHA");
        jPanel4.add(lblfecha);
        lblfecha.setBounds(106, 11, 380, 29);

        lblhora.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblhora.setForeground(new java.awt.Color(255, 255, 255));
        lblhora.setText("hora");
        jPanel4.add(lblhora);
        lblhora.setBounds(645, 11, 161, 29);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("USUARIO:");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(22, 470, 110, 29);

        lblusuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(255, 255, 255));
        lblusuario.setText("USUARIO");
        jPanel4.add(lblusuario);
        lblusuario.setBounds(136, 470, 666, 29);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(-20, 100, 1380, 510);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuSalir.setText("INICIO");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        menuSalir.add(jMenuItem1);

        jMenuBar1.add(menuSalir);

        menuVentaCredito.setText("VENTAS");

        menuVentasCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/factura.png"))); // NOI18N
        menuVentasCredito.setText("Generar Venta");
        menuVentasCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasCreditoActionPerformed(evt);
            }
        });
        menuVentaCredito.add(menuVentasCredito);

        jMenuBar1.add(menuVentaCredito);

        menuMantenimientoCategoria.setText("MANTENIMIENTO");

        menuMantenimientoarticulo.setText("Artículos");
        menuMantenimientoarticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMantenimientoarticuloActionPerformed(evt);
            }
        });
        menuMantenimientoCategoria.add(menuMantenimientoarticulo);

        menuMantenimientoClientes.setText("Clientes");
        menuMantenimientoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMantenimientoClientesActionPerformed(evt);
            }
        });
        menuMantenimientoCategoria.add(menuMantenimientoClientes);

        menuMantenimientoProveedores.setText("Proveedores");
        menuMantenimientoProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMantenimientoProveedoresActionPerformed(evt);
            }
        });
        menuMantenimientoCategoria.add(menuMantenimientoProveedores);

        menuManteCategoria.setText("Categoría");
        menuManteCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManteCategoriaActionPerformed(evt);
            }
        });
        menuMantenimientoCategoria.add(menuManteCategoria);

        menuIngresarPedido.setText("Ingresar Pedido");
        menuIngresarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarPedidoActionPerformed(evt);
            }
        });
        menuMantenimientoCategoria.add(menuIngresarPedido);

        menuUsuario.setText("Usuarios");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        menuMantenimientoCategoria.add(menuUsuario);

        jMenuBar1.add(menuMantenimientoCategoria);

        jMenu4.setText("REPORTES");

        jMenu5.setText("Ventas");

        menuVentasDiario.setText("Diario");
        menuVentasDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasDiarioActionPerformed(evt);
            }
        });
        jMenu5.add(menuVentasDiario);

        menuVentasMensual.setText("Mensual");
        menuVentasMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasMensualActionPerformed(evt);
            }
        });
        jMenu5.add(menuVentasMensual);

        MenuVentasTrimestral.setText("Trimestral");
        MenuVentasTrimestral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVentasTrimestralActionPerformed(evt);
            }
        });
        jMenu5.add(MenuVentasTrimestral);

        MenuVentasSemestral.setText("Semestral");
        MenuVentasSemestral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVentasSemestralActionPerformed(evt);
            }
        });
        jMenu5.add(MenuVentasSemestral);

        MenuVentasAnual.setText("Anual");
        MenuVentasAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVentasAnualActionPerformed(evt);
            }
        });
        jMenu5.add(MenuVentasAnual);

        jMenu4.add(jMenu5);

        jMenu6.setText("Compras");

        MenuComprasMensual.setText("Mensual");
        MenuComprasMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuComprasMensualActionPerformed(evt);
            }
        });
        jMenu6.add(MenuComprasMensual);

        MenuComprasTrimestral.setText("Trimestral");
        MenuComprasTrimestral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuComprasTrimestralActionPerformed(evt);
            }
        });
        jMenu6.add(MenuComprasTrimestral);

        MenuComprasSemestral.setText("Semestral");
        MenuComprasSemestral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuComprasSemestralActionPerformed(evt);
            }
        });
        jMenu6.add(MenuComprasSemestral);

        MenuComprasAnual.setText("Anual");
        MenuComprasAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuComprasAnualActionPerformed(evt);
            }
        });
        jMenu6.add(MenuComprasAnual);

        jMenu4.add(jMenu6);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("DEVOLUCIONES");

        MenuDevolucionProveedor.setText("Devolucion Proveedor");
        MenuDevolucionProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDevolucionProveedorActionPerformed(evt);
            }
        });
        jMenu7.add(MenuDevolucionProveedor);

        MenuDevolucionCliente.setText("Devolucion Cliente");
        MenuDevolucionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDevolucionClienteActionPerformed(evt);
            }
        });
        jMenu7.add(MenuDevolucionCliente);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuVentasCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuVentasCreditoActionPerformed

    private void menuVentasMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasMensualActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuVentasMensualActionPerformed

    private void MenuVentasTrimestralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVentasTrimestralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuVentasTrimestralActionPerformed

    private void MenuComprasMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuComprasMensualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuComprasMensualActionPerformed

    private void MenuComprasTrimestralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuComprasTrimestralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuComprasTrimestralActionPerformed

    private void MenuComprasSemestralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuComprasSemestralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuComprasSemestralActionPerformed

    private void MenuComprasAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuComprasAnualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuComprasAnualActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        // TODO add your handling code here:
        frmFactura.setVisible(true);
    }//GEN-LAST:event_btnVenderActionPerformed

    private void menuMantenimientoarticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMantenimientoarticuloActionPerformed
        // TODO add your handling code here:
        FrmProducto frmProducto=new FrmProducto();
        frmProducto.setVisible(true);
        frmProducto.setLocation(470,60);
    }//GEN-LAST:event_menuMantenimientoarticuloActionPerformed

    private void menuMantenimientoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMantenimientoClientesActionPerformed
        // TODO add your handling code here:
        FrmCliente frmCliente=new FrmCliente();
        frmCliente.setVisible(true);
        frmCliente.setLocation(470, 60);
    }//GEN-LAST:event_menuMantenimientoClientesActionPerformed

    private void menuMantenimientoProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMantenimientoProveedoresActionPerformed
        // TODO add your handling code here:
        FrmProveedor frmProveedor=new FrmProveedor();
        frmProveedor.setVisible(true);
        frmProveedor.setLocation(470,60);
    }//GEN-LAST:event_menuMantenimientoProveedoresActionPerformed

    private void menuManteCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManteCategoriaActionPerformed
        // TODO add your handling code here:
        FrmCategoria frmCategoria=new FrmCategoria();
        frmCategoria.setVisible(true);
        frmCategoria.setLocation(470, 60);
    }//GEN-LAST:event_menuManteCategoriaActionPerformed

    private void menuIngresarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuIngresarPedidoActionPerformed

    private void menuVentasDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasDiarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuVentasDiarioActionPerformed

    private void MenuVentasSemestralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVentasSemestralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuVentasSemestralActionPerformed

    private void MenuVentasAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVentasAnualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuVentasAnualActionPerformed

    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed
        // TODO add your handling code here:
            // TODO add your handling code here:
        FrmProveedor frmProveedor=new FrmProveedor();
        frmProveedor.setVisible(true);
        frmProveedor.setLocation(470,60);
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCuentaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCuentaPagarActionPerformed

    private void btnCuentaCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaCobrarActionPerformed
        // TODO add your handling code here:
        FrmCuentaCobrar cuentaCobrar=new FrmCuentaCobrar();
        cuentaCobrar.setVisible(true);
    }//GEN-LAST:event_btnCuentaCobrarActionPerformed

    private void btnIngresarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarPedidoActionPerformed

    private void MenuDevolucionProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDevolucionProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuDevolucionProveedorActionPerformed

    private void MenuDevolucionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDevolucionClienteActionPerformed
        // TODO add your handling code here:
        AnularFactura frmDevolucionCliente=new AnularFactura();
        frmDevolucionCliente.setVisible(true);
    }//GEN-LAST:event_MenuDevolucionClienteActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        // TODO add your handling code here:
        FrmUsuario frmUsuario=new FrmUsuario();
        frmUsuario.setVisible(true);
        frmUsuario.setLocation(470, 60);
    }//GEN-LAST:event_menuUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuComprasAnual;
    private javax.swing.JMenuItem MenuComprasMensual;
    private javax.swing.JMenuItem MenuComprasSemestral;
    private javax.swing.JMenuItem MenuComprasTrimestral;
    private javax.swing.JMenuItem MenuDevolucionCliente;
    private javax.swing.JMenuItem MenuDevolucionProveedor;
    private javax.swing.JMenuItem MenuVentasAnual;
    private javax.swing.JMenuItem MenuVentasSemestral;
    private javax.swing.JMenuItem MenuVentasTrimestral;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnCuentaCobrar;
    private javax.swing.JButton btnCuentaCobrar1;
    private javax.swing.JButton btnCuentaPagar;
    private javax.swing.JButton btnIngresarPedido;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    public static javax.swing.JLabel lblUsua;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblhora;
    public static javax.swing.JLabel lblusuario;
    private javax.swing.JMenuItem menuIngresarPedido;
    private javax.swing.JMenuItem menuManteCategoria;
    private javax.swing.JMenu menuMantenimientoCategoria;
    private javax.swing.JMenuItem menuMantenimientoClientes;
    private javax.swing.JMenuItem menuMantenimientoProveedores;
    private javax.swing.JMenuItem menuMantenimientoarticulo;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem menuUsuario;
    private javax.swing.JMenu menuVentaCredito;
    private javax.swing.JMenuItem menuVentasCredito;
    private javax.swing.JMenuItem menuVentasDiario;
    private javax.swing.JMenuItem menuVentasMensual;
    // End of variables declaration//GEN-END:variables

    

    @Override
    public void run() {
        Thread ct;
        ct = Thread.currentThread();
while(ct == h1) {
calcula();
lblhora.setText(hora + ":" + minutos + ":" + segundos + " "+ampm);
try {
Thread.sleep(1000);
}catch(InterruptedException e) {}
}
    }

    public void calcula () {
Calendar calendario = new GregorianCalendar();
Date fechaHoraActual = new Date();

calendario.setTime(fechaHoraActual);
ampm = calendario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
if(ampm.equals("PM")){
int h = calendario.get(Calendar.HOUR_OF_DAY)-12;
hora = h>9?""+h:"0"+h;
}else{
hora = calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY); }
minutos = calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
segundos = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
}
    
  
    
    
}
