/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DevolucionCliente;

import ConexionBD.conexionBD;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class AnularFactura extends javax.swing.JFrame {

    FrmFacturas frmFacturas=new FrmFacturas();
    int cantidadDisponible,cantDevolver,codigo;
    /**
     * Creates new form AnularFactura
     */
    public AnularFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFacturaNumero = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnAceptar1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(70, 99, 138));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("FACTURA NO.");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 50, 100, 30);
        jPanel2.add(txtFacturaNumero);
        txtFacturaNumero.setBounds(140, 50, 100, 30);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-b-icon.png"))); // NOI18N
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar);
        btnBuscar.setBounds(250, 50, 30, 23);

        jLabel2.setText("Buscar");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(250, 70, 50, 14);

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 40, 270, 50);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Fecha compra:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(340, 40, 110, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Monto:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(390, 70, 50, 30);
        jPanel2.add(txtFecha);
        txtFecha.setBounds(450, 40, 120, 30);

        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });
        jPanel2.add(txtMonto);
        txtMonto.setBounds(450, 70, 120, 30);
        jPanel2.add(txtCliente);
        txtCliente.setBounds(450, 10, 120, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Cliente:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(380, 10, 60, 30);

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Codigo", "Descripción", "Precio Unitario", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setFillsViewportHeight(true);
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setResizable(false);
            tblProductos.getColumnModel().getColumn(1).setResizable(false);
            tblProductos.getColumnModel().getColumn(2).setResizable(false);
            tblProductos.getColumnModel().getColumn(3).setResizable(false);
            tblProductos.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 560, 150);

        jCheckBox1.setText("Toda la Factura");
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(30, 290, 110, 23);

        btnAceptar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aceptar - copia.png"))); // NOI18N
        btnAceptar1.setContentAreaFilled(false);
        jPanel2.add(btnAceptar1);
        btnAceptar1.setBounds(470, 290, 30, 30);

        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar - copia.png"))); // NOI18N
        btnCancelar1.setContentAreaFilled(false);
        jPanel2.add(btnCancelar1);
        btnCancelar1.setBounds(510, 290, 30, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 30, 580, 340);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Devolución de Cliente");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 0, 234, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        FrmFacturas frmFacturas=new FrmFacturas();
        frmFacturas.setVisible(true);
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        // TODO add your handling code here:
        
        
        tblProductos.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseReleased(MouseEvent e){
                int fila = tblProductos.getSelectedRow();

                if(e.getClickCount()==2){
                    cantidadDisponible=Integer.parseInt(tblProductos.getValueAt(fila,0).toString());
                    codigo=Integer.parseInt(tblProductos.getValueAt(fila,1).toString());
                    if(cantidadDisponible>1){
                    
                        cantDevolver=Integer.parseInt(JOptionPane.showInputDialog(rootPane,"Cantidad de productos a devolver"));
                        if(cantDevolver>cantidadDisponible){
                        
                            JOptionPane.showMessageDialog(rootPane,"No se puede devolver una cantidad de productos que superan a los vendidos");
                        }
                        else{
                        
                            actualizarInventario();
                            frmFacturas.facturaNO=codigo;
                            frmFacturas.cargarDetalleFactura();
                        }
                    }
                    else{
                    
                        
                    }
                    }
                }
                
            }
       
        );
        
    }//GEN-LAST:event_tblProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnularFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnularFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnularFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnularFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnularFactura().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblProductos;
    public static javax.swing.JTextField txtCliente;
    public static javax.swing.JTextField txtFacturaNumero;
    public static javax.swing.JTextField txtFecha;
    public static javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables

    public void actualizarInventario(){
        Connection conn=conexionBD.getConnection();
        PreparedStatement ps=null;
        int cantInventario=0;
        boolean rpta=false;
        try{
            Statement stm=conn.createStatement();        
            ResultSet rs=stm.executeQuery("select * from tb_inventario where cod_producto='"+codigo+"'");
            while(rs.next()){
            
                cantInventario=rs.getInt("stock");
            }
            cantDevolver=cantDevolver+cantInventario;
            String call= "{CALL pa_modificar_inventario(?,?)}";
            ps=conn.prepareCall(call);
            ps.setInt(1, codigo);
            ps.setInt(2, cantDevolver);
            
            rpta=ps.executeUpdate()==1? true:false;
            }catch(SQLException sqlex){
            setTitle("Problema CargarDatos" +sqlex.getMessage());}
    }
}
