/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Producto;

import ConexionBD.conexionBD;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class MantProducto extends javax.swing.JFrame {

    double impuesto1;
    double impuesto;
    double precioCompra;
    double precioVenta;
    Producto producto=new Producto();
    static boolean nuevo=false;
    /**
     * Creates new form MantProducto
     */
    public MantProducto() {
        initComponents();
        cargarCategorias();
        cargarProveedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCant = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox();
        comboProveedor = new javax.swing.JComboBox();
        checkExonerado = new javax.swing.JCheckBox();
        lblProveedor = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        txtImpuesto = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblPrecioCompra = new javax.swing.JLabel();
        lblPrecioVenta = new javax.swing.JLabel();
        lblCate = new javax.swing.JLabel();
        lblProvee = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(70, 99, 138));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Código:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 10, 60, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Descripción:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(170, 10, 78, 30);

        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });
        jPanel2.add(txtDescripcion);
        txtDescripcion.setBounds(170, 40, 130, 30);

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCodigo);
        txtCodigo.setBounds(20, 40, 130, 30);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar - copia.png"))); // NOI18N
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(260, 260, 40, 40);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aceptar - copia.png"))); // NOI18N
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar);
        btnAceptar.setBounds(210, 260, 40, 40);

        jLabel3.setText("Cancelar");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(260, 300, 50, 14);

        jLabel4.setText("Aceptar");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(210, 300, 50, 14);

        txtPrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioCompraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioCompraKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrecioCompra);
        txtPrecioCompra.setBounds(20, 100, 130, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("P.Compra:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 70, 70, 30);
        jPanel2.add(txtPrecioVenta);
        txtPrecioVenta.setBounds(170, 100, 130, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("P.Venta:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(170, 70, 60, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Proveedor:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(170, 130, 70, 30);

        lblCant.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCant.setText("Cantidad:");
        jPanel2.add(lblCant);
        lblCant.setBounds(20, 190, 70, 30);

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar" }));
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(comboCategoria);
        comboCategoria.setBounds(20, 160, 130, 30);

        comboProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar" }));
        comboProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(comboProveedor);
        comboProveedor.setBounds(170, 160, 130, 30);

        checkExonerado.setBackground(new java.awt.Color(255, 255, 255));
        checkExonerado.setText("Exonerado");
        checkExonerado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkExoneradoActionPerformed(evt);
            }
        });
        jPanel2.add(checkExonerado);
        checkExonerado.setBounds(230, 190, 90, 30);
        jPanel2.add(lblProveedor);
        lblProveedor.setBounds(90, 340, 50, 30);
        jPanel2.add(lblCategoria);
        lblCategoria.setBounds(30, 340, 50, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Categoria:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 130, 70, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Impuesto:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(170, 190, 70, 30);
        jPanel2.add(txtCant);
        txtCant.setBounds(20, 220, 130, 30);
        jPanel2.add(txtImpuesto);
        txtImpuesto.setBounds(170, 220, 130, 30);

        lblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setText("Digite solo letras");
        jPanel2.add(lblDescripcion);
        lblDescripcion.setBounds(250, 10, 90, 30);

        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo.setText("digite solo numeros");
        jPanel2.add(lblCodigo);
        lblCodigo.setBounds(70, 10, 90, 30);

        lblPrecioCompra.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioCompra.setText("digite solo numeros");
        jPanel2.add(lblPrecioCompra);
        lblPrecioCompra.setBounds(90, 70, 80, 30);

        lblPrecioVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioVenta.setText("digite solo numeros");
        jPanel2.add(lblPrecioVenta);
        lblPrecioVenta.setBounds(230, 70, 80, 30);

        lblCate.setForeground(new java.awt.Color(255, 255, 255));
        lblCate.setText("digite solo numeros");
        jPanel2.add(lblCate);
        lblCate.setBounds(90, 130, 80, 30);

        lblProvee.setForeground(new java.awt.Color(255, 255, 255));
        lblProvee.setText("digite solo numeros");
        jPanel2.add(lblProvee);
        lblProvee.setBounds(240, 130, 80, 30);

        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("digite solo numeros");
        jPanel2.add(lblCantidad);
        lblCantidad.setBounds(80, 190, 80, 30);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("PRODUCTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkExoneradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkExoneradoActionPerformed
        // TODO add your handling code here:
        if(checkExonerado.isSelected())
        {
             impuesto1=Double.parseDouble(txtImpuesto.getText().toString());
             txtImpuesto.setText(String.valueOf(0));
        }
        else{ txtImpuesto.setText(String.valueOf(impuesto1));} 
      
    }//GEN-LAST:event_checkExoneradoActionPerformed

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed
        // TODO add your handling code here
        //int codigo=comboCategoria.getSelectedIndex();
        //txtCategoria.setText(String.valueOf(codigo));
        Connection conn;
        try{
            
            conn=conexionBD.getConnection();
            Statement stm=conn.createStatement();
            ResultSet rs=stm.executeQuery("select * from tb_categoria where nombre='"+comboCategoria.getSelectedItem()+"'");
            rs.next();
            lblCategoria.setText(String.valueOf(rs.getInt("cod_categoria")));
            lblCategoria.setVisible(false);
        }
        catch (Exception e){
        
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_comboCategoriaActionPerformed

    private void comboProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProveedorActionPerformed
        // TODO add your handling code here:
        Connection conn;
        try{
        
            conn=conexionBD.getConnection();
            Statement stm=conn.createStatement();
            ResultSet rs=stm.executeQuery("select cedula_juridica from tb_proveedor where nombre='"+comboProveedor.getSelectedItem()+"'");
            rs.next();
            lblProveedor.setText(rs.getString("cedula_juridica"));
            lblProveedor.setVisible(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_comboProveedorActionPerformed

    private void txtPrecioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCompraKeyTyped
        // TODO add your handling code here:
         char car = evt.getKeyChar();

        if(txtPrecioCompra.getText().length()>=7) evt.consume();
        if((car<'0' || car>'9')) {evt.consume(); lblPrecioCompra.setText("Sólo números");
            lblPrecioCompra.setForeground(Color.red);}else{lblPrecioCompra.setForeground(Color.white);}
        if(txtPrecioCompra.getText().equals("")){lblPrecioCompra.setForeground(Color.white);}
        txtPrecioCompra.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                if (!txtPrecioCompra.getText().equals("")) {
                    calculaImpuesto_venta();
                }
            }
        });
    }//GEN-LAST:event_txtPrecioCompraKeyTyped

    private void txtPrecioCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCompraKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioCompraKeyReleased

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if(txtCodigo.getText().length()>=15) evt.consume();
        if((car<'0' || car>'9')) {evt.consume(); lblCodigo.setText("Sólo números");
            lblCodigo.setForeground(Color.red);}else{lblCodigo.setForeground(Color.white);}
        if(txtCodigo.getText().equals("")){lblCodigo.setForeground(Color.white);}

    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if(txtDescripcion.getText().length()>=15) evt.consume();
        if((car<'a' || car>'z') && (car<'A' || car>'Z')) {evt.consume(); lblDescripcion.setText("Sólo letras");
            lblDescripcion.setForeground(Color.red);}else{lblDescripcion.setForeground(Color.white);}
        if(txtDescripcion.getText().equals("")){lblDescripcion.setForeground(Color.white);}
    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        String mensaje=validarCampos();
        if(mensaje.equals("")){
            boolean exonerado=checkExonerado.isSelected();

            if(nuevo==true){

                try {
                    // TODO add your handling code here:
                    producto.setCod_producto(Integer.parseInt(txtCodigo.getText()));
                    producto.setDescripcion(txtDescripcion.getText());
                    producto.setCod_categoria(Integer.parseInt(lblCategoria.getText()));
                    producto.setCed_proveedor(lblProveedor.getText());
                    producto.setPrecio_compra(Double.parseDouble(txtPrecioCompra.getText()));
                    producto.setPrecio_venta(Double.parseDouble(txtPrecioVenta.getText()));
                    producto.setImpuesto(Double.parseDouble(txtImpuesto.getText()));
                    producto.setExonerado(exonerado);
                    producto.setCant(Integer.parseInt(txtCant.getText().toString()));
                    BDProducto.insertarProducto(producto);
                } catch (SQLException ex) {
                    Logger.getLogger(MantProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(rootPane,"Se ha registrado con éxito el nuevo producto","Registro con éxito",JOptionPane.PLAIN_MESSAGE);
                this.dispose();
            }
            else{
                try {
                    producto.setCod_producto(Integer.parseInt(txtCodigo.getText()));
                    producto.setDescripcion(txtDescripcion.getText());
                    producto.setCod_categoria(Integer.parseInt(lblCategoria.getText()));
                    producto.setCed_proveedor(lblProveedor.getText());
                    producto.setPrecio_compra(Double.parseDouble(txtPrecioCompra.getText()));
                    producto.setPrecio_venta(Double.parseDouble(txtPrecioVenta.getText()));
                    producto.setImpuesto(Double.parseDouble(txtImpuesto.getText()));
                    producto.setExonerado(exonerado);
                    BDProducto.modificarProducto(producto);
                } catch (SQLException ex) {
                    Logger.getLogger(MantProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(rootPane,"Se ha actualizado con éxito el cliente","Actualización con éxito",JOptionPane.PLAIN_MESSAGE);
                this.dispose();

            }
            txtCodigo.setText("");
            txtDescripcion.setText("");
            lblCategoria.setText("");
            txtPrecioCompra.setText("");
            txtPrecioVenta.setText("");
        }
        else{JOptionPane.showMessageDialog(rootPane, mensaje,"ERROR",JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantProducto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    public static javax.swing.JCheckBox checkExonerado;
    public static javax.swing.JComboBox comboCategoria;
    public static javax.swing.JComboBox comboProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblCant;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCate;
    public static javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblPrecioCompra;
    private javax.swing.JLabel lblPrecioVenta;
    private javax.swing.JLabel lblProvee;
    public static javax.swing.JLabel lblProveedor;
    public static javax.swing.JLabel lblTitulo;
    public static javax.swing.JTextField txtCant;
    public static javax.swing.JTextField txtCodigo;
    public static javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtImpuesto;
    public static javax.swing.JTextField txtPrecioCompra;
    public static javax.swing.JTextField txtPrecioVenta;
    // End of variables declaration//GEN-END:variables

    public void cargarCategorias(){
    
        
        Connection conn;
        try{
        
            conn=conexionBD.getConnection();
            Statement stm=conn.createStatement();
            ResultSet rs=stm.executeQuery("select * from tb_categoria");
            while(rs.next()){
                
                String categorias=rs.getString("nombre");
                comboCategoria.addItem(categorias);
                               
            }conn.close();
            }catch(SQLException sqlex){
            setTitle("Problema CargarDatos" +sqlex.getMessage());}
        
    }
    
    public void cargarProveedores(){
    
        
        Connection conn;
        try{
        
            conn=conexionBD.getConnection();
            Statement stm=conn.createStatement();
            ResultSet rs=stm.executeQuery("select * from tb_proveedor");
            while(rs.next()){
                
                String categorias=rs.getString("nombre");
                comboProveedor.addItem(categorias);
                               
            }conn.close();
            }catch(SQLException sqlex){
            setTitle("Problema CargarDatos" +sqlex.getMessage());}
        
    }
    
    public void calculaImpuesto_venta(){
    
        try {
        
            txtPrecioVenta.setEditable(false);
            precioCompra=Integer.parseInt(txtPrecioCompra.getText());
            precioVenta=precioCompra*0.25+precioCompra;
            impuesto=precioCompra*0.13;
            txtPrecioVenta.setText(String.valueOf(precioVenta));
            txtImpuesto.setText(String.valueOf(impuesto));
        }
        catch(Exception e){JOptionPane.showMessageDialog(rootPane, e);}
    }
    
         private String validarCampos(){
    
        String msj="";
        if(txtCodigo.getText().equals("")){
        
            msj="Por favor ingrese la código del producto";
            txtCodigo.requestFocus();
            return msj;
        }
        
         if(txtDescripcion.getText().equals("")){
        
            msj="Por favor ingrese la descripción del producto";
            txtDescripcion.requestFocus();
            return msj;
        }
         
         if(txtPrecioCompra.getText().equals("")){
        
            msj="Por favor ingrese el precio de compra del producto";
            txtPrecioCompra.requestFocus();
            return msj;
        }
        
         if(comboCategoria.getSelectedItem()=="Seleccionar"){
        
            msj="Por favor seleccione una categoria";
            comboCategoria.requestFocus();
            return msj;
        }
         
         if(comboProveedor.getSelectedItem()=="Seleccionar"){
        
            msj="Por favor seleccione un proveedor";
            comboProveedor.requestFocus();
            return msj;
        }
        
        
        return msj;
        
    }
}

