/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuario;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class MantUsuario extends javax.swing.JFrame {

    Usuario usuario=new Usuario();
    boolean nuevo=false;
    /**
     * Creates new form MantUsuario
     */
    public MantUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboNivel = new javax.swing.JComboBox();
        lblCedula = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        lblClave = new javax.swing.JLabel();
        lblPuesto = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MANTENIMIENTO");

        jPanel1.setBackground(new java.awt.Color(70, 99, 138));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Cédula:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(14, 11, 49, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(160, 10, 53, 30);

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombre);
        txtNombre.setBounds(160, 40, 130, 30);

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        jPanel2.add(txtCedula);
        txtCedula.setBounds(10, 40, 130, 30);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar - copia.png"))); // NOI18N
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(250, 190, 40, 40);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aceptar - copia.png"))); // NOI18N
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar);
        btnAceptar.setBounds(200, 190, 40, 40);

        jLabel3.setText("Cancelar");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(250, 230, 50, 14);

        jLabel4.setText("Aceptar");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(200, 230, 50, 14);

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel2.add(txtApellido);
        txtApellido.setBounds(10, 100, 130, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Apellido:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 70, 60, 30);

        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
        });
        jPanel2.add(txtTel);
        txtTel.setBounds(160, 100, 130, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Tel:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(160, 70, 30, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Clave:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 130, 50, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Puesto:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(160, 130, 60, 30);

        comboNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vendedor", "Administrador" }));
        jPanel2.add(comboNivel);
        comboNivel.setBounds(160, 160, 130, 30);

        lblCedula.setForeground(new java.awt.Color(255, 255, 255));
        lblCedula.setText("jLabel8");
        jPanel2.add(lblCedula);
        lblCedula.setBounds(70, 14, 90, 20);

        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("jLabel8");
        jPanel2.add(lblNombre);
        lblNombre.setBounds(220, 14, 70, 20);

        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("jLabel8");
        jPanel2.add(lblApellido);
        lblApellido.setBounds(70, 74, 70, 20);

        lblTel.setForeground(new java.awt.Color(255, 255, 255));
        lblTel.setText("jLabel8");
        jPanel2.add(lblTel);
        lblTel.setBounds(190, 74, 90, 20);

        lblClave.setForeground(new java.awt.Color(255, 255, 255));
        lblClave.setText("jLabel8");
        jPanel2.add(lblClave);
        lblClave.setBounds(50, 134, 90, 20);

        lblPuesto.setForeground(new java.awt.Color(255, 255, 255));
        lblPuesto.setText("jLabel8");
        jPanel2.add(lblPuesto);
        lblPuesto.setBounds(210, 134, 80, 20);
        jPanel2.add(txtClave);
        txtClave.setBounds(10, 160, 130, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        if(nuevo==true){

            try {
                // TODO add your handling code here:
                usuario.setCedula(txtCedula.getText());
                usuario.setNombre(txtNombre.getText());
                usuario.setApellido(txtApellido.getText());
                usuario.setTel(txtTel.getText());
                usuario.setClave(txtClave.getText());
                usuario.setPuesto(comboNivel.getSelectedItem().toString());
                BDUsuario.insertarUsuario(usuario);
            } catch (SQLException ex) {
                Logger.getLogger(MantUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane,"Se ha registrado con éxito el nuevo usuario","Registro con éxito",JOptionPane.PLAIN_MESSAGE);
            this.dispose();
        }
        else{
            try {
                usuario.setCedula(txtCedula.getText());
                usuario.setNombre(txtNombre.getText());
                usuario.setApellido(txtApellido.getText());
                usuario.setTel(txtTel.getText());
                usuario.setClave(txtClave.getText());
                usuario.setPuesto(comboNivel.getSelectedItem().toString());
                BDUsuario.modificarUsuario(usuario);
            } catch (SQLException ex) {
                Logger.getLogger(MantUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane,"Se ha actualizado con éxito el usuario","Actualización con éxito",JOptionPane.PLAIN_MESSAGE);
            this.dispose();

        }
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtTel.setText("");
        txtClave.setText("");

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if(txtCedula.getText().length()>=15) evt.consume();
        if((car<'0' || car>'9')) {evt.consume(); lblCedula.setText("Solo números");
            lblCedula.setForeground(Color.red);}else{lblCedula.setForeground(Color.white);}
        if(txtCedula.getText().equals("")){lblCedula.setForeground(Color.white);}
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
         char car = evt.getKeyChar();

        if(txtNombre.getText().length()>=15) evt.consume();
        if((car<'a' || car>'z') && (car<'A' || car>'Z')) {evt.consume(); lblNombre.setText("Solo letras");
            lblNombre.setForeground(Color.red);}else{lblNombre.setForeground(Color.white);}
        if(txtNombre.getText().equals("")){lblNombre.setForeground(Color.white);}
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if(txtApellido.getText().length()>=15) evt.consume();
        if((car<'a' || car>'z') && (car<'A' || car>'Z')) {evt.consume(); lblApellido.setText("Solo letras");
            lblApellido.setForeground(Color.red);}else{lblApellido.setForeground(Color.white);}
        if(txtApellido.getText().equals("")){lblApellido.setForeground(Color.white);}
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
        // TODO add your handling code here:
         char car = evt.getKeyChar();

        if(txtTel.getText().length()>=15) evt.consume();
        if((car<'0' || car>'9')) {evt.consume(); lblTel.setText("Solo números");
            lblTel.setForeground(Color.red);}else{lblTel.setForeground(Color.white);}
        if(txtTel.getText().equals("")){lblTel.setForeground(Color.white);}
    }//GEN-LAST:event_txtTelKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox comboNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblTel;
    public static javax.swing.JTextField txtApellido;
    public static javax.swing.JTextField txtCedula;
    public static javax.swing.JPasswordField txtClave;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
