/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Facturacion;

import ConexionBD.conexionBD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonathan
 */
public class FrmFactura extends javax.swing.JFrame {

    java.util.Date utilDate = new java.util.Date();
    java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
    Calendar calendario = Calendar.getInstance();
    double sub =0,neto=0;
    int dia=calendario.get(Calendar.DAY_OF_MONTH);
    int mes=calendario.get(Calendar.MONTH);
    int anio=calendario.get(Calendar.YEAR);
    public String ced;
    Factura factura=new Factura();
    int factura_NO;
    double montoTotal=0;
    double IV=0,impuesto;
    double subTotal=0,subTotalFijo=0;
    int codigo;
   
    /**
     * Creates new form Factura
     */
    public FrmFactura() {
        initComponents();
        lblFecha.setText(dia+"/"+mes+"/"+anio);
        obtenerNumFactura();
        txtCliente.setText("Contado");
        txtCliente.setEditable(false);
        lblCedCliente.setText("1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        txtNeto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtImpuesto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        checkBoxDescuento = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        txtCliente = new javax.swing.JTextField();
        btnCliente = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        comboPago = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        lblVence = new javax.swing.JLabel();
        lblFactura = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnRemover = new javax.swing.JButton();
        lblCedCliente = new javax.swing.JLabel();
        lblCredito = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(70, 99, 138));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("CÉDULA JURIDICA 3-101-3126-36-15");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 90, 310, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("PAGO:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(460, 140, 50, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("FILADELFIA,CARRILLO,GTE");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 50, 310, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("COMERCIAL CACHAGUI S.A");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 70, 310, 20);

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 20, 320, 100);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Gaceta 171 pag.8 del 05/09/97");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 490, 310, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("FACTURA NO.");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(410, 20, 100, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("FECHA:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(450, 50, 60, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("VENCE:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(450, 80, 60, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("CÓDIGO:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 140, 70, 30);
        jPanel2.add(txtCodigo);
        txtCodigo.setBounds(90, 140, 100, 30);

        jLabel14.setText("Agregar");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(210, 160, 50, 13);

        tblProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Código", "Descripción", "Precio Unitario", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setFillsViewportHeight(true);
        tblProductos.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblProductos);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 190, 670, 200);

        txtNeto.setEditable(false);
        txtNeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetoActionPerformed(evt);
            }
        });
        jPanel2.add(txtNeto);
        txtNeto.setBounds(500, 510, 160, 30);

        jLabel18.setText("Remover");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(260, 160, 60, 13);

        txtSubtotal.setEditable(false);
        txtSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        txtSubtotal.setText("0");
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });
        jPanel2.add(txtSubtotal);
        txtSubtotal.setBounds(500, 420, 160, 30);

        txtDescuento.setEditable(false);
        jPanel2.add(txtDescuento);
        txtDescuento.setBounds(500, 450, 160, 30);

        txtImpuesto.setEditable(false);
        txtImpuesto.setForeground(new java.awt.Color(255, 255, 255));
        txtImpuesto.setText("0");
        jPanel2.add(txtImpuesto);
        txtImpuesto.setBounds(500, 480, 160, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Subtotal:");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(440, 420, 60, 30);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Imp.Venta:");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(430, 480, 70, 30);

        checkBoxDescuento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkBoxDescuento.setText("Descuento:");
        checkBoxDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxDescuentoActionPerformed(evt);
            }
        });
        jPanel2.add(checkBoxDescuento);
        checkBoxDescuento.setBounds(400, 450, 100, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Neto a Cobrar:");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(400, 510, 100, 30);

        jLabel22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Monto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N
        jPanel2.add(jLabel22);
        jLabel22.setBounds(380, 390, 300, 160);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("LIBRERÍA Y BAZAR LETTY TeleFax 2688-8537");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(20, 30, 310, 20);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_to_shopping_cart.png"))); // NOI18N
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar);
        btnAgregar.setBounds(220, 130, 30, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Autorizado por dirección general de tributación");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(50, 450, 310, 20);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("directa mediante la resolución 11-97, artículo NO.7 ");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(50, 470, 310, 20);

        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel17);
        jLabel17.setBounds(40, 440, 300, 80);

        jLabel24.setText("Cancelar");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(610, 580, 50, 13);

        jLabel25.setText("Aceptar");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(550, 580, 50, 13);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar - copia.png"))); // NOI18N
        btnCancelar.setContentAreaFilled(false);
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(610, 550, 40, 33);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aceptar - copia.png"))); // NOI18N
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar);
        btnAceptar.setBounds(550, 550, 40, 33);
        jPanel2.add(txtCliente);
        txtCliente.setBounds(510, 110, 130, 30);

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_user.png"))); // NOI18N
        btnCliente.setContentAreaFilled(false);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnCliente);
        btnCliente.setBounds(650, 110, 30, 30);

        jLabel26.setText("Buscar");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(650, 140, 40, 13);

        comboPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Efectivo", "Crédito" }));
        comboPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPagoActionPerformed(evt);
            }
        });
        jPanel2.add(comboPago);
        comboPago.setBounds(510, 140, 130, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("CLIENTE:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(440, 110, 70, 30);

        lblVence.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(lblVence);
        lblVence.setBounds(510, 80, 130, 30);

        lblFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(lblFactura);
        lblFactura.setBounds(510, 20, 130, 30);

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(lblFecha);
        lblFecha.setBounds(510, 50, 130, 30);

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/remove_from_shopping_cart.png"))); // NOI18N
        btnRemover.setContentAreaFilled(false);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemover);
        btnRemover.setBounds(270, 130, 30, 30);
        jPanel2.add(lblCedCliente);
        lblCedCliente.setBounds(350, 130, 0, 0);

        lblCredito.setForeground(new java.awt.Color(255, 255, 255));
        lblCredito.setText("jLabel15");
        jPanel2.add(lblCredito);
        lblCredito.setBounds(370, 130, 38, 13);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("GENERAR FACTURA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxDescuentoActionPerformed
        // TODO add your handling code here:
        
        if(checkBoxDescuento.isSelected())
        {
             sub=Double.parseDouble(txtSubtotal.getText().toString());
             neto=Double.parseDouble(txtNeto.getText().toString());
             JOptionPane.showMessageDialog(rootPane,sub);
             double porcentaje=Double.parseDouble(JOptionPane.showInputDialog(null,"Digite el porcentaje de descuento","DESCUENTO",JOptionPane.PLAIN_MESSAGE));
             double porcentaje1=sub*porcentaje;
             JOptionPane.showMessageDialog(rootPane,porcentaje1);
             double descuento=sub-porcentaje1;
             JOptionPane.showMessageDialog(rootPane,descuento);
             double imp=Double.parseDouble(txtImpuesto.getText().toString());
             descuento=descuento+imp;
             txtDescuento.setText(String.valueOf(porcentaje1));
             txtNeto.setText(String.valueOf(descuento));
        }
        else{ txtNeto.setText(String.valueOf(neto));txtDescuento.setText("0");} 
    }//GEN-LAST:event_checkBoxDescuentoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String mensaje=validarCampos();
        if(mensaje.equals("")){
        
        try {
            // TODO add your handling code here:
                double Credito=Double.parseDouble(lblCredito.getText().toString());
                double Neto=Double.parseDouble(txtNeto.getText().toString());
                if(Credito<Neto){
                
                    JOptionPane.showMessageDialog(rootPane,"El total supera el crédito");
                    tblProductos.requestFocus();
                }
                else{
            crearFactura();
            insertarDetalle();
                this.dispose();}
        } catch (SQLException ex) {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
        else{JOptionPane.showMessageDialog(rootPane, mensaje,"ERROR",JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        FrmCliente frmCliente=new FrmCliente();
        frmCliente.setVisible(true);
        frmCliente.setLocation(500, 100);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        FrmProducto frmProducto=new FrmProducto();
        frmProducto.setVisible(true);
        frmProducto.setLocation(500,100);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelTblProductos = (DefaultTableModel) tblProductos.getModel(); //TableProducto es el nombre de mi tabla ;) 
        int fila=tblProductos.getSelectedRow();
        int cant=Integer.parseInt(tblProductos.getValueAt(fila, 0).toString());
        //double impuesto=Double.parseDouble(FrmProducto.tblProductos.getValueAt(dia, cant))
        codigo=Integer.parseInt(tblProductos.getValueAt(fila,1).toString());
        double subtotal=Double.parseDouble(tblProductos.getValueAt(fila,4).toString());
        double sub=Double.parseDouble(txtSubtotal.getText());
        double subF=sub-subtotal;
        double imp=obtenerImpuesto();
        double desImp=cant*imp;
        double iV=Double.parseDouble(txtImpuesto.getText().toString());
        iV=iV-desImp;
        txtSubtotal.setText(String.valueOf(subF));
        txtImpuesto.setText(String.valueOf(iV));
        double Neto=iV+subF;
        txtNeto.setText(String.valueOf(Neto));
        modelTblProductos.removeRow(tblProductos.getSelectedRow()); 


    }//GEN-LAST:event_btnRemoverActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtNetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetoActionPerformed

    private void comboPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPagoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFactura().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnRemover;
    private javax.swing.JCheckBox checkBoxDescuento;
    private javax.swing.JComboBox comboPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblCedCliente;
    public static javax.swing.JLabel lblCredito;
    private javax.swing.JLabel lblFactura;
    public static javax.swing.JLabel lblFecha;
    public static javax.swing.JLabel lblVence;
    public static javax.swing.JTable tblProductos;
    public static javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigo;
    public static javax.swing.JTextField txtDescuento;
    public static javax.swing.JTextField txtImpuesto;
    public static javax.swing.JTextField txtNeto;
    public static javax.swing.JTextField txtSubtotal;
    // End of variables declaration//GEN-END:variables

    public void obtenerNumFactura() {
    
        Connection conn=conexionBD.getConnection();
        try{
                       
            Statement stm=conn.createStatement();
            ResultSet rs=stm.executeQuery("select * from tb_factura");
            while(rs.next()){
            
                factura_NO=rs.getInt("factura_NO");
                factura_NO=factura_NO+1;
                lblFactura.setText(String.valueOf(factura_NO));
               
            }
            if(factura_NO==0){
            factura_NO=factura_NO+1;
            lblFactura.setText(String.valueOf(factura_NO));
            }   
            conn.close();
        }catch(Exception e){JOptionPane.showMessageDialog(rootPane, e);}
    }
    
    public void crearFactura() {
        
        mes=mes+1;
        String fecha1=String.valueOf(anio+"-"+mes+"-"+dia).toString();
        
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        try{
                Date fecha = formatoFecha.parse(fecha1);
                java.sql.Date sqlDate1 = new java.sql.Date(fecha.getTime());
                factura.setFactura_NO(factura_NO);
                factura.setFecha(sqlDate1);
                Object pago=comboPago.getSelectedItem();
                if(pago.equals("Crédito")){factura.setContado(false);}                              
                if(pago.equals("Efectivo")){factura.setContado(true);
                factura.setCliente(lblCedCliente.getText());
                factura.setSubtotal(Double.parseDouble(txtSubtotal.getText()));
                factura.setImpuesto(Double.parseDouble(txtImpuesto.getText()));
                factura.setDescuento(Double.parseDouble(txtDescuento.getText()));
                factura.setTotal(Double.parseDouble(txtNeto.getText()));
                FacturaBD.insertarFactura(factura);
                }
            }catch (SQLException ex) {
                    Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void insertarDetalle() throws SQLException{
        int fila = 0;
        int cantidad = 0,codProducto = 0;
        fila = tblProductos.getRowCount();
        String descripcion = null;
        double precio = 0,subtot = 0;
        DetalleFactura detalleFactura=new DetalleFactura();
        for (int f = 0; f < fila; f++) {
            cantidad = Integer.parseInt(tblProductos.getValueAt(f, 0).toString());
            codProducto=Integer.parseInt(tblProductos.getValueAt(f, 1).toString());
            descripcion=String.valueOf(tblProductos.getValueAt(f, 2).toString());
            precio=Double.parseDouble(tblProductos.getValueAt(f,3).toString());
            subtot=Double.parseDouble(tblProductos.getValueAt(f,4).toString());
             detalleFactura.setFactura_NO(factura_NO);
        detalleFactura.setCantidad(cantidad);
        detalleFactura.setCod_producto(codProducto);
        detalleFactura.setDescripcion(descripcion);
        detalleFactura.setPrecio(precio);
        detalleFactura.setSubtotal(subtot);
        DetalleFacturaBD.insertarProducto(detalleFactura);
        }
       
        
                JOptionPane.showMessageDialog(rootPane,"Se ha registrado con éxito la nueva categoria","Registro con éxito",JOptionPane.PLAIN_MESSAGE);
                this.dispose();
    }
    
    public void calcularSubtotal(){
            int fila = 0;
            IV = 0.0;
            montoTotal = 0.0;
            //fila = ListaProductoV.getRowCount();
            fila = tblProductos.getRowCount();
            JOptionPane.showMessageDialog(rootPane, fila);
            montoTotal = 0.0;
            //fila = ListaProductoV.getRowCount();
            for (int f = 0; f < fila; f++) {
                subTotal = Double.parseDouble( tblProductos.getValueAt(f, 4).toString());
                JOptionPane.showMessageDialog(rootPane,subTotal);
                subTotalFijo=subTotalFijo+subTotal;
                //montoTotal = Double.parseDouble(txtIGV.getText()) + Double.parseDouble(txtSubTotal.getText());
                //txtMontoApagar.setText(String.valueOf(montoTotal));
            }
            
        }
    
    private String validarCampos(){
    
        int fila=tblProductos.getRowCount();
        String msj="";
               
         if(comboPago.getSelectedItem().equals("Seleccione")){
        
            msj="Por favor seleccione el tipo de pago";
            comboPago.requestFocus();
            return msj;
        }
         
         if(fila==0){
        
            msj="Por favor ingrese productos a la factura";
            return msj;
        }
               
        return msj;
        
        
    }
    
    private double obtenerImpuesto(){
    
        Connection conn=conexionBD.getConnection();
        try{
                       
            Statement stm=conn.createStatement();
            ResultSet rs=stm.executeQuery("select * from tb_producto where cod_producto='"+codigo+"'");
            while(rs.next()){
            
                impuesto=rs.getDouble("impuesto");
               
            }   
            conn.close();
            return impuesto;
        }catch(Exception e){JOptionPane.showMessageDialog(rootPane, e);}
        return 0;
        
    }
    
    }

