/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Cuentas;

/**
 *
 * @author Jonathan
 */
public class CuentaCobrar2 extends javax.swing.JFrame {

    /**
     * Creates new form AbonarFactura2
     */
    public CuentaCobrar2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtRecibo = new javax.swing.JTextField();
        txtClienteNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSumaDe = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtReciboDe = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAbonos = new javax.swing.JTable();
        btnAceptar1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aceptar.png"))); // NOI18N
        btnAceptar.setContentAreaFilled(false);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelar.setContentAreaFilled(false);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("MANTENIMIENTO USUARIOS");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Abono a factura");

        jPanel1.setBackground(new java.awt.Color(70, 99, 138));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("CÉDULA JURIDICA 3-101-3126-36-15");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 90, 310, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("FECHA:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(360, 100, 90, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("COMERCIAL CACHAGUI S.A");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 70, 310, 20);

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 20, 320, 100);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("LIBRERÍA Y BAZAR LETTY TeleFax 288-8537");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 30, 310, 20);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("LIBRERÍA Y BAZAR LETTY TeleFax 288-8537");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(20, 30, 310, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("FILADELFIA,CARRILLO,GTE");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 50, 310, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("RECIBO NO.");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(360, 20, 90, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("CLIENTE NO.");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(360, 60, 90, 30);
        jPanel2.add(txtFecha);
        txtFecha.setBounds(450, 100, 160, 30);
        jPanel2.add(txtRecibo);
        txtRecibo.setBounds(450, 20, 160, 30);
        jPanel2.add(txtClienteNumero);
        txtClienteNumero.setBounds(450, 60, 160, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("La suma de:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(60, 150, 80, 17);
        jPanel2.add(txtSumaDe);
        txtSumaDe.setBounds(150, 180, 470, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Hemos recibido de:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 180, 130, 17);
        jPanel2.add(txtReciboDe);
        txtReciboDe.setBounds(150, 150, 470, 20);

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 140, 630, 70);

        tblAbonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Factura NO.", "Ult.Abono", "Saldo anterior", "Intereses", "Amortización", "Total pago", "Saldo actual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAbonos.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(tblAbonos);
        if (tblAbonos.getColumnModel().getColumnCount() > 0) {
            tblAbonos.getColumnModel().getColumn(0).setResizable(false);
            tblAbonos.getColumnModel().getColumn(1).setResizable(false);
            tblAbonos.getColumnModel().getColumn(2).setResizable(false);
            tblAbonos.getColumnModel().getColumn(3).setResizable(false);
            tblAbonos.getColumnModel().getColumn(4).setResizable(false);
            tblAbonos.getColumnModel().getColumn(5).setResizable(false);
            tblAbonos.getColumnModel().getColumn(6).setResizable(false);
            tblAbonos.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 630, 90);

        btnAceptar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aceptar.png"))); // NOI18N
        btnAceptar1.setContentAreaFilled(false);
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar1);
        btnAceptar1.setBounds(500, 340, 60, 60);

        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelar1.setContentAreaFilled(false);
        jPanel2.add(btnCancelar1);
        btnCancelar1.setBounds(570, 340, 60, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 30, 650, 370);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Abonar Factura");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 0, 166, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAceptar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuentaCobrar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuentaCobrar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuentaCobrar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuentaCobrar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuentaCobrar2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblAbonos;
    public static javax.swing.JTextField txtClienteNumero;
    public static javax.swing.JTextField txtFecha;
    public static javax.swing.JTextField txtRecibo;
    private javax.swing.JTextField txtReciboDe;
    private javax.swing.JTextField txtSumaDe;
    // End of variables declaration//GEN-END:variables
}
