/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Cuentas;

import ConexionBD.conexionBD;
import static Producto.FrmProducto.tblProductos;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Jonathan
 */
public class FrmCuentaCobrar extends javax.swing.JFrame {
Connection conn;
        DefaultTableModel temp;
    int factura;
    String fecha,nombre,apellido;
    int cliente,filas=0;
    double subtotal,impuesto,descuento,total,saldo;
            CuentaCobrar2 cuentaCobrar2=new CuentaCobrar2();

    /**
     * Creates new form FrmCuentaCobrar
     */
    public FrmCuentaCobrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacturas = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(70, 99, 138));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("CLIENTE:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 37, 62, 30);

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        jPanel2.add(txtCliente);
        txtCliente.setBounds(130, 40, 159, 30);

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_user.png"))); // NOI18N
        btnBuscarCliente.setContentAreaFilled(false);
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarCliente);
        btnBuscarCliente.setBounds(290, 40, 65, 41);

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 10, 350, 80);

        tblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Factura NO.", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFacturas.setFillsViewportHeight(true);
        tblFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFacturas);
        if (tblFacturas.getColumnModel().getColumnCount() > 0) {
            tblFacturas.getColumnModel().getColumn(0).setResizable(false);
            tblFacturas.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 470, 170);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar - copia.png"))); // NOI18N
        btnCancelar.setContentAreaFilled(false);
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(450, 290, 30, 30);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aceptar - copia.png"))); // NOI18N
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar);
        btnAceptar.setBounds(410, 290, 30, 30);

        jLabel5.setText("Monto:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 280, 40, 50);

        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });
        jPanel2.add(txtMonto);
        txtMonto.setBounds(50, 290, 100, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 28, 490, 350);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CUENTAS POR COBRAR");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 0, 370, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        FrmCliente frmCliente=new FrmCliente();
        frmCliente.setVisible(true);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void tblFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFacturasMouseClicked
        // TODO add your handling code here:
        
        tblFacturas.addMouseListener(new MouseAdapter(){
           @Override
           public void mouseReleased(MouseEvent e){
           
               int fila = tblFacturas.getSelectedRow();
            if(e.getClickCount()==2){
             factura=Integer.parseInt(tblFacturas.getValueAt(fila,0).toString());
             try{
             FrmFactura frmFactura=new FrmFactura();
            conn=conexionBD.getConnection();
            Statement stm=conn.createStatement();
            ResultSet rs=stm.executeQuery("select * from tb_factura where factura_NO='"+factura+"'");
            while(rs.next()){
                
                fecha=rs.getString("fecha");
                cliente=rs.getInt("cliente");
                subtotal=rs.getDouble("subtotal");
                descuento=rs.getDouble("descuento");
                impuesto=rs.getDouble("impuesto");
                total=rs.getDouble("total");
                
            }
            ResultSet rss=stm.executeQuery("select * from tb_cliente where cedula_cliente='"+cliente+"'");
            while(rss.next()){
                nombre=rss.getString("nombre");
                apellido=rss.getString("apellido");
            }
            FrmFactura.lblFactura.setText(String.valueOf(factura));
            FrmFactura.lblFecha.setText(fecha);
            FrmFactura.lblCliente.setText(nombre+" "+apellido);
            FrmFactura.txtSubtotal.setText(String.valueOf(subtotal));
            FrmFactura.txtSubtotal.setForeground(Color.black);
            FrmFactura.txtDescuento.setText(String.valueOf(descuento));
            FrmFactura.txtImpuesto.setText(String.valueOf(impuesto));
            FrmFactura.txtImpuesto.setForeground(Color.black);
            FrmFactura.txtNeto.setText(String.valueOf(total));
            
            ResultSet rsss=stm.executeQuery("select cantidad as Cantidad,cod_producto as Código,"
                    + "descripcion as Descripción,precio as Precio,subtotal as Subtotal from tb_detalle_factura where factura_NO='"+factura+"'");
            temp=new DefaultTableModel();
            ResultSetMetaData md=rsss.getMetaData();
            int columnas= md.getColumnCount();
            for (int i = 1; i <= columnas; i++) {
            temp.addColumn(md.getColumnLabel(i));}
            while(rsss.next()){
            Object[] filas = new Object[columnas];
            for (int i = 0; i < columnas; i++) {filas[i]=rsss.getObject(i+1);}
            temp.addRow(filas);
            }FrmFactura.tblProductos.setModel(temp);
            frmFactura.setVisible(true);
            conn.close();
            
            }catch(SQLException sqlex){
            setTitle("Problema CargarDatos" +sqlex.getMessage());}
                //cerrar();
           }
           }
           }
                   );
        
    }//GEN-LAST:event_tblFacturasMouseClicked

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        int fila = tblFacturas.getSelectedRow();
        double abono=Double.parseDouble(JOptionPane.showInputDialog("Digite el total del abono"));
        factura=Integer.parseInt(tblFacturas.getValueAt(fila,0).toString());
        saldo=Double.parseDouble(tblFacturas.getValueAt(fila, 1).toString());
        try{
            conn=conexionBD.getConnection();
            Statement stm=conn.createStatement();
            ResultSet rs=stm.executeQuery("select * from tb_factura where factura_NO='"+factura+"'");
            while(rs.next()){
                
                fecha=rs.getString("fecha");
                cliente=rs.getInt("cliente");
            }
            CuentaCobrar2.txtFecha.setText(fecha);
            CuentaCobrar2.txtClienteNumero.setText(String.valueOf(cliente));
            ObtenerAbono();
            cuentaCobrar2.setVisible(true);
            conn.close();
            
            }catch(SQLException sqlex){
            setTitle("Problema CargarDatos" +sqlex.getMessage());}   
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCuentaCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCuentaCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCuentaCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCuentaCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCuentaCobrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblFacturas;
    public static javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables

   public void cerrar(){this.dispose();}
   
   public void ObtenerAbono(){
  
       int abono1 = 0;
        double abonoAnterior = 0,saldoAnterior = 0;
        Connection conn=conexionBD.getConnection();
        try{
                       
            Statement stm=conn.createStatement();
            ResultSet abono=stm.executeQuery("select * from tb_abono_cliente");
            while(abono.next()){
                abono1=abono.getInt("id_abono");
                abono1++;
                
            }
            if(abono1==0){abono1++;}
            ResultSet rs=stm.executeQuery("select * from tb_abono_cliente where id_abono='"+abono1+"'");
            while(rs.next()){
                abonoAnterior=Double.parseDouble(rs.getString("total_abono"));
            }
            int fila=tblFacturas.getSelectedRow();
            factura=Integer.parseInt(tblFacturas.getValueAt(fila, 0).toString());
            JOptionPane.showMessageDialog(rootPane, factura);
           /* ResultSet rss=stm.executeQuery("select saldo from tb_cuenta_cobrar where factura_NO='"+factura+"'");
            while(rss.next()){
                saldoAnterior=Double.parseDouble(rs.getString("saldo"));
            }*/
            conn.close();
            DefaultTableModel modeloDeMiTabla=(DefaultTableModel)CuentaCobrar2.tblAbonos.getModel();

            modeloDeMiTabla.addRow(new Object[filas]);
                    
            CuentaCobrar2.tblAbonos.setModel(modeloDeMiTabla);
            CuentaCobrar2.txtRecibo.setText(String.valueOf(abono1));
            CuentaCobrar2.tblAbonos.setValueAt(abonoAnterior, 0, 2);
            CuentaCobrar2.tblAbonos.setValueAt(saldoAnterior, 0, 3);
            
        }catch(Exception e){JOptionPane.showMessageDialog(rootPane, e);}
        filas++;
   }
   
}
